/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Vintage1986RouteImport } from './routes/vintage-1986'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SharePreviewRouteImport } from './routes/share-preview'
import { Route as SafetyReportRouteImport } from './routes/safety-report'
import { Route as RichieRouteImport } from './routes/richie'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MolinoPizzaPopUpRouteImport } from './routes/molino-pizza-pop-up'
import { Route as MolinoJune6RouteImport } from './routes/molino-june-6'
import { Route as MolinoRouteImport } from './routes/molino'
import { Route as MealPrepRouteImport } from './routes/meal-prep'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IrieSupperClubRouteImport } from './routes/irie-supper-club'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as HostRouteImport } from './routes/host'
import { Route as FoundingSalonRouteImport } from './routes/founding-salon'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TastemakersIndexRouteImport } from './routes/tastemakers.index'
import { Route as TastemakersApplyRouteImport } from './routes/tastemakers.apply'
import { Route as TastemakersTastemakerIdRouteImport } from './routes/tastemakers.$tastemakerId'
import { Route as TablesTableIdRouteImport } from './routes/tables.$tableId'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as E2eShareCardPriceRouteImport } from './routes/e2e.share-card-price'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as ChefsRichieMillionJrRouteImport } from './routes/chefs.richie-million-jr'
import { Route as ChefsMosheFhimaRouteImport } from './routes/chefs.moshe-fhima'
import { Route as ChefsChefIdRouteImport } from './routes/chefs.$chefId'
import { Route as ChefHandleRouteImport } from './routes/chef.$handle'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminTastemakersRouteImport } from './routes/admin.tastemakers'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminPaymentsGoLiveRouteImport } from './routes/admin.payments-go-live'
import { Route as AdminMolinoRouteImport } from './routes/admin.molino'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminChefServiceInfoRouteImport } from './routes/admin.chef-service-info'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedEmailTestRouteImport } from './routes/_authenticated/email-test'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChefbotRouteImport } from './routes/_authenticated/chefbot'
import { Route as AuthenticatedChefRouteImport } from './routes/_authenticated/chef'
import { Route as AuthenticatedBringThisHomeRouteImport } from './routes/_authenticated/bring-this-home'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApplyStatusIdRouteImport } from './routes/apply.status.$id'
import { Route as ApiPublicHostApplicationRouteImport } from './routes/api/public/host-application'
import { Route as AdminPreviewAddressUpdateRouteImport } from './routes/admin.preview.address-update'
import { Route as AuthenticatedReviewTableIdRouteImport } from './routes/_authenticated/review.$tableId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedHostEventsRouteImport } from './routes/_authenticated/host.events'
import { Route as AuthenticatedHostDashboardRouteImport } from './routes/_authenticated/host.dashboard'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHostApplicationResendRouteImport } from './routes/api/public/host-application.resend'
import { Route as ApiPublicHooksProcessOrderRemindersRouteImport } from './routes/api/public/hooks/process-order-reminders'
import { Route as ApiPublicHooksPaymentsGoLiveReminderRouteImport } from './routes/api/public/hooks/payments-go-live-reminder'
import { Route as AuthenticatedTastemakersTastemakerIdUploadRouteImport } from './routes/_authenticated/tastemakers.$tastemakerId.upload'

const Vintage1986Route = Vintage1986RouteImport.update({
  id: '/vintage-1986',
  path: '/vintage-1986',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePreviewRoute = SharePreviewRouteImport.update({
  id: '/share-preview',
  path: '/share-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyReportRoute = SafetyReportRouteImport.update({
  id: '/safety-report',
  path: '/safety-report',
  getParentRoute: () => rootRouteImport,
} as any)
const RichieRoute = RichieRouteImport.update({
  id: '/richie',
  path: '/richie',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MolinoPizzaPopUpRoute = MolinoPizzaPopUpRouteImport.update({
  id: '/molino-pizza-pop-up',
  path: '/molino-pizza-pop-up',
  getParentRoute: () => rootRouteImport,
} as any)
const MolinoJune6Route = MolinoJune6RouteImport.update({
  id: '/molino-june-6',
  path: '/molino-june-6',
  getParentRoute: () => rootRouteImport,
} as any)
const MolinoRoute = MolinoRouteImport.update({
  id: '/molino',
  path: '/molino',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPrepRoute = MealPrepRouteImport.update({
  id: '/meal-prep',
  path: '/meal-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IrieSupperClubRoute = IrieSupperClubRouteImport.update({
  id: '/irie-supper-club',
  path: '/irie-supper-club',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundingSalonRoute = FoundingSalonRouteImport.update({
  id: '/founding-salon',
  path: '/founding-salon',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TastemakersIndexRoute = TastemakersIndexRouteImport.update({
  id: '/tastemakers/',
  path: '/tastemakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TastemakersApplyRoute = TastemakersApplyRouteImport.update({
  id: '/tastemakers/apply',
  path: '/tastemakers/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const TastemakersTastemakerIdRoute = TastemakersTastemakerIdRouteImport.update({
  id: '/tastemakers/$tastemakerId',
  path: '/tastemakers/$tastemakerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesTableIdRoute = TablesTableIdRouteImport.update({
  id: '/tables/$tableId',
  path: '/tables/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/listings/$slug',
  path: '/listings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eShareCardPriceRoute = E2eShareCardPriceRouteImport.update({
  id: '/e2e/share-card-price',
  path: '/e2e/share-card-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsRichieMillionJrRoute = ChefsRichieMillionJrRouteImport.update({
  id: '/chefs/richie-million-jr',
  path: '/chefs/richie-million-jr',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsMosheFhimaRoute = ChefsMosheFhimaRouteImport.update({
  id: '/chefs/moshe-fhima',
  path: '/chefs/moshe-fhima',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsChefIdRoute = ChefsChefIdRouteImport.update({
  id: '/chefs/$chefId',
  path: '/chefs/$chefId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefHandleRoute = ChefHandleRouteImport.update({
  id: '/chef/$handle',
  path: '/chef/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTastemakersRoute = AdminTastemakersRouteImport.update({
  id: '/admin/tastemakers',
  path: '/admin/tastemakers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsGoLiveRoute = AdminPaymentsGoLiveRouteImport.update({
  id: '/admin/payments-go-live',
  path: '/admin/payments-go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMolinoRoute = AdminMolinoRouteImport.update({
  id: '/admin/molino',
  path: '/admin/molino',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChefServiceInfoRoute = AdminChefServiceInfoRouteImport.update({
  id: '/admin/chef-service-info',
  path: '/admin/chef-service-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailTestRoute = AuthenticatedEmailTestRouteImport.update({
  id: '/email-test',
  path: '/email-test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChefbotRoute = AuthenticatedChefbotRouteImport.update({
  id: '/chefbot',
  path: '/chefbot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChefRoute = AuthenticatedChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBringThisHomeRoute =
  AuthenticatedBringThisHomeRouteImport.update({
    id: '/bring-this-home',
    path: '/bring-this-home',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyStatusIdRoute = ApplyStatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => ApplyRoute,
} as any)
const ApiPublicHostApplicationRoute =
  ApiPublicHostApplicationRouteImport.update({
    id: '/api/public/host-application',
    path: '/api/public/host-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPreviewAddressUpdateRoute =
  AdminPreviewAddressUpdateRouteImport.update({
    id: '/admin/preview/address-update',
    path: '/admin/preview/address-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReviewTableIdRoute =
  AuthenticatedReviewTableIdRouteImport.update({
    id: '/review/$tableId',
    path: '/review/$tableId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostEventsRoute = AuthenticatedHostEventsRouteImport.update({
  id: '/host/events',
  path: '/host/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostDashboardRoute =
  AuthenticatedHostDashboardRouteImport.update({
    id: '/host/dashboard',
    path: '/host/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHostApplicationResendRoute =
  ApiPublicHostApplicationResendRouteImport.update({
    id: '/resend',
    path: '/resend',
    getParentRoute: () => ApiPublicHostApplicationRoute,
  } as any)
const ApiPublicHooksProcessOrderRemindersRoute =
  ApiPublicHooksProcessOrderRemindersRouteImport.update({
    id: '/api/public/hooks/process-order-reminders',
    path: '/api/public/hooks/process-order-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaymentsGoLiveReminderRoute =
  ApiPublicHooksPaymentsGoLiveReminderRouteImport.update({
    id: '/api/public/hooks/payments-go-live-reminder',
    path: '/api/public/hooks/payments-go-live-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTastemakersTastemakerIdUploadRoute =
  AuthenticatedTastemakersTastemakerIdUploadRouteImport.update({
    id: '/tastemakers/$tastemakerId/upload',
    path: '/tastemakers/$tastemakerId/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRouteWithChildren
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/founding-salon': typeof FoundingSalonRoute
  '/host': typeof HostRoute
  '/hosts': typeof HostsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/irie-supper-club': typeof IrieSupperClubRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/meal-prep': typeof MealPrepRoute
  '/molino': typeof MolinoRoute
  '/molino-june-6': typeof MolinoJune6Route
  '/molino-pizza-pop-up': typeof MolinoPizzaPopUpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/richie': typeof RichieRoute
  '/safety-report': typeof SafetyReportRoute
  '/share-preview': typeof SharePreviewRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vintage-1986': typeof Vintage1986Route
  '/bring-this-home': typeof AuthenticatedBringThisHomeRoute
  '/chef': typeof AuthenticatedChefRoute
  '/chefbot': typeof AuthenticatedChefbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-test': typeof AuthenticatedEmailTestRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/chef-service-info': typeof AdminChefServiceInfoRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/molino': typeof AdminMolinoRoute
  '/admin/payments-go-live': typeof AdminPaymentsGoLiveRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tastemakers': typeof AdminTastemakersRoute
  '/api/chat': typeof ApiChatRoute
  '/chef/$handle': typeof ChefHandleRoute
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/chefs/moshe-fhima': typeof ChefsMosheFhimaRoute
  '/chefs/richie-million-jr': typeof ChefsRichieMillionJrRoute
  '/e/$slug': typeof ESlugRoute
  '/e2e/share-card-price': typeof E2eShareCardPriceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tastemakers/$tastemakerId': typeof TastemakersTastemakerIdRoute
  '/tastemakers/apply': typeof TastemakersApplyRoute
  '/tastemakers/': typeof TastemakersIndexRoute
  '/host/dashboard': typeof AuthenticatedHostDashboardRoute
  '/host/events': typeof AuthenticatedHostEventsRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/review/$tableId': typeof AuthenticatedReviewTableIdRoute
  '/admin/preview/address-update': typeof AdminPreviewAddressUpdateRoute
  '/api/public/host-application': typeof ApiPublicHostApplicationRouteWithChildren
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tastemakers/$tastemakerId/upload': typeof AuthenticatedTastemakersTastemakerIdUploadRoute
  '/api/public/hooks/payments-go-live-reminder': typeof ApiPublicHooksPaymentsGoLiveReminderRoute
  '/api/public/hooks/process-order-reminders': typeof ApiPublicHooksProcessOrderRemindersRoute
  '/api/public/host-application/resend': typeof ApiPublicHostApplicationResendRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRouteWithChildren
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/founding-salon': typeof FoundingSalonRoute
  '/host': typeof HostRoute
  '/hosts': typeof HostsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/irie-supper-club': typeof IrieSupperClubRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/meal-prep': typeof MealPrepRoute
  '/molino': typeof MolinoRoute
  '/molino-june-6': typeof MolinoJune6Route
  '/molino-pizza-pop-up': typeof MolinoPizzaPopUpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/richie': typeof RichieRoute
  '/safety-report': typeof SafetyReportRoute
  '/share-preview': typeof SharePreviewRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vintage-1986': typeof Vintage1986Route
  '/bring-this-home': typeof AuthenticatedBringThisHomeRoute
  '/chef': typeof AuthenticatedChefRoute
  '/chefbot': typeof AuthenticatedChefbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-test': typeof AuthenticatedEmailTestRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/chef-service-info': typeof AdminChefServiceInfoRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/molino': typeof AdminMolinoRoute
  '/admin/payments-go-live': typeof AdminPaymentsGoLiveRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tastemakers': typeof AdminTastemakersRoute
  '/api/chat': typeof ApiChatRoute
  '/chef/$handle': typeof ChefHandleRoute
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/chefs/moshe-fhima': typeof ChefsMosheFhimaRoute
  '/chefs/richie-million-jr': typeof ChefsRichieMillionJrRoute
  '/e/$slug': typeof ESlugRoute
  '/e2e/share-card-price': typeof E2eShareCardPriceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tastemakers/$tastemakerId': typeof TastemakersTastemakerIdRoute
  '/tastemakers/apply': typeof TastemakersApplyRoute
  '/tastemakers': typeof TastemakersIndexRoute
  '/host/dashboard': typeof AuthenticatedHostDashboardRoute
  '/host/events': typeof AuthenticatedHostEventsRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/review/$tableId': typeof AuthenticatedReviewTableIdRoute
  '/admin/preview/address-update': typeof AdminPreviewAddressUpdateRoute
  '/api/public/host-application': typeof ApiPublicHostApplicationRouteWithChildren
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tastemakers/$tastemakerId/upload': typeof AuthenticatedTastemakersTastemakerIdUploadRoute
  '/api/public/hooks/payments-go-live-reminder': typeof ApiPublicHooksPaymentsGoLiveReminderRoute
  '/api/public/hooks/process-order-reminders': typeof ApiPublicHooksProcessOrderRemindersRoute
  '/api/public/host-application/resend': typeof ApiPublicHostApplicationResendRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRouteWithChildren
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/founding-salon': typeof FoundingSalonRoute
  '/host': typeof HostRoute
  '/hosts': typeof HostsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/irie-supper-club': typeof IrieSupperClubRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/meal-prep': typeof MealPrepRoute
  '/molino': typeof MolinoRoute
  '/molino-june-6': typeof MolinoJune6Route
  '/molino-pizza-pop-up': typeof MolinoPizzaPopUpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/richie': typeof RichieRoute
  '/safety-report': typeof SafetyReportRoute
  '/share-preview': typeof SharePreviewRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vintage-1986': typeof Vintage1986Route
  '/_authenticated/bring-this-home': typeof AuthenticatedBringThisHomeRoute
  '/_authenticated/chef': typeof AuthenticatedChefRoute
  '/_authenticated/chefbot': typeof AuthenticatedChefbotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-test': typeof AuthenticatedEmailTestRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/chef-service-info': typeof AdminChefServiceInfoRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/molino': typeof AdminMolinoRoute
  '/admin/payments-go-live': typeof AdminPaymentsGoLiveRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tastemakers': typeof AdminTastemakersRoute
  '/api/chat': typeof ApiChatRoute
  '/chef/$handle': typeof ChefHandleRoute
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/chefs/moshe-fhima': typeof ChefsMosheFhimaRoute
  '/chefs/richie-million-jr': typeof ChefsRichieMillionJrRoute
  '/e/$slug': typeof ESlugRoute
  '/e2e/share-card-price': typeof E2eShareCardPriceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tastemakers/$tastemakerId': typeof TastemakersTastemakerIdRoute
  '/tastemakers/apply': typeof TastemakersApplyRoute
  '/tastemakers/': typeof TastemakersIndexRoute
  '/_authenticated/host/dashboard': typeof AuthenticatedHostDashboardRoute
  '/_authenticated/host/events': typeof AuthenticatedHostEventsRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/review/$tableId': typeof AuthenticatedReviewTableIdRoute
  '/admin/preview/address-update': typeof AdminPreviewAddressUpdateRoute
  '/api/public/host-application': typeof ApiPublicHostApplicationRouteWithChildren
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/tastemakers/$tastemakerId/upload': typeof AuthenticatedTastemakersTastemakerIdUploadRoute
  '/api/public/hooks/payments-go-live-reminder': typeof ApiPublicHooksPaymentsGoLiveReminderRoute
  '/api/public/hooks/process-order-reminders': typeof ApiPublicHooksProcessOrderRemindersRoute
  '/api/public/host-application/resend': typeof ApiPublicHostApplicationResendRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/community'
    | '/discover'
    | '/founding-salon'
    | '/host'
    | '/hosts'
    | '/how-it-works'
    | '/irie-supper-club'
    | '/join'
    | '/login'
    | '/meal-prep'
    | '/molino'
    | '/molino-june-6'
    | '/molino-pizza-pop-up'
    | '/privacy'
    | '/reset-password'
    | '/richie'
    | '/safety-report'
    | '/share-preview'
    | '/signup'
    | '/terms'
    | '/unsubscribe'
    | '/vintage-1986'
    | '/bring-this-home'
    | '/chef'
    | '/chefbot'
    | '/dashboard'
    | '/email-test'
    | '/favorites'
    | '/settings'
    | '/admin/chef-service-info'
    | '/admin/contacts'
    | '/admin/inbox'
    | '/admin/molino'
    | '/admin/payments-go-live'
    | '/admin/reviews'
    | '/admin/tastemakers'
    | '/api/chat'
    | '/chef/$handle'
    | '/chefs/$chefId'
    | '/chefs/moshe-fhima'
    | '/chefs/richie-million-jr'
    | '/e/$slug'
    | '/e2e/share-card-price'
    | '/email/unsubscribe'
    | '/listings/$slug'
    | '/tables/$tableId'
    | '/tastemakers/$tastemakerId'
    | '/tastemakers/apply'
    | '/tastemakers/'
    | '/host/dashboard'
    | '/host/events'
    | '/orders/$orderId'
    | '/review/$tableId'
    | '/admin/preview/address-update'
    | '/api/public/host-application'
    | '/apply/status/$id'
    | '/lovable/email/suppression'
    | '/tastemakers/$tastemakerId/upload'
    | '/api/public/hooks/payments-go-live-reminder'
    | '/api/public/hooks/process-order-reminders'
    | '/api/public/host-application/resend'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/community'
    | '/discover'
    | '/founding-salon'
    | '/host'
    | '/hosts'
    | '/how-it-works'
    | '/irie-supper-club'
    | '/join'
    | '/login'
    | '/meal-prep'
    | '/molino'
    | '/molino-june-6'
    | '/molino-pizza-pop-up'
    | '/privacy'
    | '/reset-password'
    | '/richie'
    | '/safety-report'
    | '/share-preview'
    | '/signup'
    | '/terms'
    | '/unsubscribe'
    | '/vintage-1986'
    | '/bring-this-home'
    | '/chef'
    | '/chefbot'
    | '/dashboard'
    | '/email-test'
    | '/favorites'
    | '/settings'
    | '/admin/chef-service-info'
    | '/admin/contacts'
    | '/admin/inbox'
    | '/admin/molino'
    | '/admin/payments-go-live'
    | '/admin/reviews'
    | '/admin/tastemakers'
    | '/api/chat'
    | '/chef/$handle'
    | '/chefs/$chefId'
    | '/chefs/moshe-fhima'
    | '/chefs/richie-million-jr'
    | '/e/$slug'
    | '/e2e/share-card-price'
    | '/email/unsubscribe'
    | '/listings/$slug'
    | '/tables/$tableId'
    | '/tastemakers/$tastemakerId'
    | '/tastemakers/apply'
    | '/tastemakers'
    | '/host/dashboard'
    | '/host/events'
    | '/orders/$orderId'
    | '/review/$tableId'
    | '/admin/preview/address-update'
    | '/api/public/host-application'
    | '/apply/status/$id'
    | '/lovable/email/suppression'
    | '/tastemakers/$tastemakerId/upload'
    | '/api/public/hooks/payments-go-live-reminder'
    | '/api/public/hooks/process-order-reminders'
    | '/api/public/host-application/resend'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/apply'
    | '/community'
    | '/discover'
    | '/founding-salon'
    | '/host'
    | '/hosts'
    | '/how-it-works'
    | '/irie-supper-club'
    | '/join'
    | '/login'
    | '/meal-prep'
    | '/molino'
    | '/molino-june-6'
    | '/molino-pizza-pop-up'
    | '/privacy'
    | '/reset-password'
    | '/richie'
    | '/safety-report'
    | '/share-preview'
    | '/signup'
    | '/terms'
    | '/unsubscribe'
    | '/vintage-1986'
    | '/_authenticated/bring-this-home'
    | '/_authenticated/chef'
    | '/_authenticated/chefbot'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-test'
    | '/_authenticated/favorites'
    | '/_authenticated/settings'
    | '/admin/chef-service-info'
    | '/admin/contacts'
    | '/admin/inbox'
    | '/admin/molino'
    | '/admin/payments-go-live'
    | '/admin/reviews'
    | '/admin/tastemakers'
    | '/api/chat'
    | '/chef/$handle'
    | '/chefs/$chefId'
    | '/chefs/moshe-fhima'
    | '/chefs/richie-million-jr'
    | '/e/$slug'
    | '/e2e/share-card-price'
    | '/email/unsubscribe'
    | '/listings/$slug'
    | '/tables/$tableId'
    | '/tastemakers/$tastemakerId'
    | '/tastemakers/apply'
    | '/tastemakers/'
    | '/_authenticated/host/dashboard'
    | '/_authenticated/host/events'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/review/$tableId'
    | '/admin/preview/address-update'
    | '/api/public/host-application'
    | '/apply/status/$id'
    | '/lovable/email/suppression'
    | '/_authenticated/tastemakers/$tastemakerId/upload'
    | '/api/public/hooks/payments-go-live-reminder'
    | '/api/public/hooks/process-order-reminders'
    | '/api/public/host-application/resend'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  DiscoverRoute: typeof DiscoverRoute
  FoundingSalonRoute: typeof FoundingSalonRoute
  HostRoute: typeof HostRoute
  HostsRoute: typeof HostsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IrieSupperClubRoute: typeof IrieSupperClubRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MealPrepRoute: typeof MealPrepRoute
  MolinoRoute: typeof MolinoRoute
  MolinoJune6Route: typeof MolinoJune6Route
  MolinoPizzaPopUpRoute: typeof MolinoPizzaPopUpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RichieRoute: typeof RichieRoute
  SafetyReportRoute: typeof SafetyReportRoute
  SharePreviewRoute: typeof SharePreviewRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Vintage1986Route: typeof Vintage1986Route
  AdminChefServiceInfoRoute: typeof AdminChefServiceInfoRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminMolinoRoute: typeof AdminMolinoRoute
  AdminPaymentsGoLiveRoute: typeof AdminPaymentsGoLiveRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminTastemakersRoute: typeof AdminTastemakersRoute
  ApiChatRoute: typeof ApiChatRoute
  ChefHandleRoute: typeof ChefHandleRoute
  ChefsChefIdRoute: typeof ChefsChefIdRoute
  ChefsMosheFhimaRoute: typeof ChefsMosheFhimaRoute
  ChefsRichieMillionJrRoute: typeof ChefsRichieMillionJrRoute
  ESlugRoute: typeof ESlugRoute
  E2eShareCardPriceRoute: typeof E2eShareCardPriceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ListingsSlugRoute: typeof ListingsSlugRoute
  TablesTableIdRoute: typeof TablesTableIdRoute
  TastemakersTastemakerIdRoute: typeof TastemakersTastemakerIdRoute
  TastemakersApplyRoute: typeof TastemakersApplyRoute
  TastemakersIndexRoute: typeof TastemakersIndexRoute
  AdminPreviewAddressUpdateRoute: typeof AdminPreviewAddressUpdateRoute
  ApiPublicHostApplicationRoute: typeof ApiPublicHostApplicationRouteWithChildren
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksPaymentsGoLiveReminderRoute: typeof ApiPublicHooksPaymentsGoLiveReminderRoute
  ApiPublicHooksProcessOrderRemindersRoute: typeof ApiPublicHooksProcessOrderRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vintage-1986': {
      id: '/vintage-1986'
      path: '/vintage-1986'
      fullPath: '/vintage-1986'
      preLoaderRoute: typeof Vintage1986RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-preview': {
      id: '/share-preview'
      path: '/share-preview'
      fullPath: '/share-preview'
      preLoaderRoute: typeof SharePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-report': {
      id: '/safety-report'
      path: '/safety-report'
      fullPath: '/safety-report'
      preLoaderRoute: typeof SafetyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/richie': {
      id: '/richie'
      path: '/richie'
      fullPath: '/richie'
      preLoaderRoute: typeof RichieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molino-pizza-pop-up': {
      id: '/molino-pizza-pop-up'
      path: '/molino-pizza-pop-up'
      fullPath: '/molino-pizza-pop-up'
      preLoaderRoute: typeof MolinoPizzaPopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molino-june-6': {
      id: '/molino-june-6'
      path: '/molino-june-6'
      fullPath: '/molino-june-6'
      preLoaderRoute: typeof MolinoJune6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molino': {
      id: '/molino'
      path: '/molino'
      fullPath: '/molino'
      preLoaderRoute: typeof MolinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-prep': {
      id: '/meal-prep'
      path: '/meal-prep'
      fullPath: '/meal-prep'
      preLoaderRoute: typeof MealPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irie-supper-club': {
      id: '/irie-supper-club'
      path: '/irie-supper-club'
      fullPath: '/irie-supper-club'
      preLoaderRoute: typeof IrieSupperClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founding-salon': {
      id: '/founding-salon'
      path: '/founding-salon'
      fullPath: '/founding-salon'
      preLoaderRoute: typeof FoundingSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tastemakers/': {
      id: '/tastemakers/'
      path: '/tastemakers'
      fullPath: '/tastemakers/'
      preLoaderRoute: typeof TastemakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tastemakers/apply': {
      id: '/tastemakers/apply'
      path: '/tastemakers/apply'
      fullPath: '/tastemakers/apply'
      preLoaderRoute: typeof TastemakersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tastemakers/$tastemakerId': {
      id: '/tastemakers/$tastemakerId'
      path: '/tastemakers/$tastemakerId'
      fullPath: '/tastemakers/$tastemakerId'
      preLoaderRoute: typeof TastemakersTastemakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$tableId': {
      id: '/tables/$tableId'
      path: '/tables/$tableId'
      fullPath: '/tables/$tableId'
      preLoaderRoute: typeof TablesTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/listings/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/share-card-price': {
      id: '/e2e/share-card-price'
      path: '/e2e/share-card-price'
      fullPath: '/e2e/share-card-price'
      preLoaderRoute: typeof E2eShareCardPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs/richie-million-jr': {
      id: '/chefs/richie-million-jr'
      path: '/chefs/richie-million-jr'
      fullPath: '/chefs/richie-million-jr'
      preLoaderRoute: typeof ChefsRichieMillionJrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs/moshe-fhima': {
      id: '/chefs/moshe-fhima'
      path: '/chefs/moshe-fhima'
      fullPath: '/chefs/moshe-fhima'
      preLoaderRoute: typeof ChefsMosheFhimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs/$chefId': {
      id: '/chefs/$chefId'
      path: '/chefs/$chefId'
      fullPath: '/chefs/$chefId'
      preLoaderRoute: typeof ChefsChefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/$handle': {
      id: '/chef/$handle'
      path: '/chef/$handle'
      fullPath: '/chef/$handle'
      preLoaderRoute: typeof ChefHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tastemakers': {
      id: '/admin/tastemakers'
      path: '/admin/tastemakers'
      fullPath: '/admin/tastemakers'
      preLoaderRoute: typeof AdminTastemakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments-go-live': {
      id: '/admin/payments-go-live'
      path: '/admin/payments-go-live'
      fullPath: '/admin/payments-go-live'
      preLoaderRoute: typeof AdminPaymentsGoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/molino': {
      id: '/admin/molino'
      path: '/admin/molino'
      fullPath: '/admin/molino'
      preLoaderRoute: typeof AdminMolinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chef-service-info': {
      id: '/admin/chef-service-info'
      path: '/admin/chef-service-info'
      fullPath: '/admin/chef-service-info'
      preLoaderRoute: typeof AdminChefServiceInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-test': {
      id: '/_authenticated/email-test'
      path: '/email-test'
      fullPath: '/email-test'
      preLoaderRoute: typeof AuthenticatedEmailTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chefbot': {
      id: '/_authenticated/chefbot'
      path: '/chefbot'
      fullPath: '/chefbot'
      preLoaderRoute: typeof AuthenticatedChefbotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chef': {
      id: '/_authenticated/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof AuthenticatedChefRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bring-this-home': {
      id: '/_authenticated/bring-this-home'
      path: '/bring-this-home'
      fullPath: '/bring-this-home'
      preLoaderRoute: typeof AuthenticatedBringThisHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/status/$id': {
      id: '/apply/status/$id'
      path: '/status/$id'
      fullPath: '/apply/status/$id'
      preLoaderRoute: typeof ApplyStatusIdRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/api/public/host-application': {
      id: '/api/public/host-application'
      path: '/api/public/host-application'
      fullPath: '/api/public/host-application'
      preLoaderRoute: typeof ApiPublicHostApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preview/address-update': {
      id: '/admin/preview/address-update'
      path: '/admin/preview/address-update'
      fullPath: '/admin/preview/address-update'
      preLoaderRoute: typeof AdminPreviewAddressUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review/$tableId': {
      id: '/_authenticated/review/$tableId'
      path: '/review/$tableId'
      fullPath: '/review/$tableId'
      preLoaderRoute: typeof AuthenticatedReviewTableIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host/events': {
      id: '/_authenticated/host/events'
      path: '/host/events'
      fullPath: '/host/events'
      preLoaderRoute: typeof AuthenticatedHostEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host/dashboard': {
      id: '/_authenticated/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof AuthenticatedHostDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/host-application/resend': {
      id: '/api/public/host-application/resend'
      path: '/resend'
      fullPath: '/api/public/host-application/resend'
      preLoaderRoute: typeof ApiPublicHostApplicationResendRouteImport
      parentRoute: typeof ApiPublicHostApplicationRoute
    }
    '/api/public/hooks/process-order-reminders': {
      id: '/api/public/hooks/process-order-reminders'
      path: '/api/public/hooks/process-order-reminders'
      fullPath: '/api/public/hooks/process-order-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessOrderRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/payments-go-live-reminder': {
      id: '/api/public/hooks/payments-go-live-reminder'
      path: '/api/public/hooks/payments-go-live-reminder'
      fullPath: '/api/public/hooks/payments-go-live-reminder'
      preLoaderRoute: typeof ApiPublicHooksPaymentsGoLiveReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tastemakers/$tastemakerId/upload': {
      id: '/_authenticated/tastemakers/$tastemakerId/upload'
      path: '/tastemakers/$tastemakerId/upload'
      fullPath: '/tastemakers/$tastemakerId/upload'
      preLoaderRoute: typeof AuthenticatedTastemakersTastemakerIdUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBringThisHomeRoute: typeof AuthenticatedBringThisHomeRoute
  AuthenticatedChefRoute: typeof AuthenticatedChefRoute
  AuthenticatedChefbotRoute: typeof AuthenticatedChefbotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailTestRoute: typeof AuthenticatedEmailTestRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedHostDashboardRoute: typeof AuthenticatedHostDashboardRoute
  AuthenticatedHostEventsRoute: typeof AuthenticatedHostEventsRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedReviewTableIdRoute: typeof AuthenticatedReviewTableIdRoute
  AuthenticatedTastemakersTastemakerIdUploadRoute: typeof AuthenticatedTastemakersTastemakerIdUploadRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBringThisHomeRoute: AuthenticatedBringThisHomeRoute,
  AuthenticatedChefRoute: AuthenticatedChefRoute,
  AuthenticatedChefbotRoute: AuthenticatedChefbotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailTestRoute: AuthenticatedEmailTestRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedHostDashboardRoute: AuthenticatedHostDashboardRoute,
  AuthenticatedHostEventsRoute: AuthenticatedHostEventsRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedReviewTableIdRoute: AuthenticatedReviewTableIdRoute,
  AuthenticatedTastemakersTastemakerIdUploadRoute:
    AuthenticatedTastemakersTastemakerIdUploadRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApplyRouteChildren {
  ApplyStatusIdRoute: typeof ApplyStatusIdRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyStatusIdRoute: ApplyStatusIdRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface ApiPublicHostApplicationRouteChildren {
  ApiPublicHostApplicationResendRoute: typeof ApiPublicHostApplicationResendRoute
}

const ApiPublicHostApplicationRouteChildren: ApiPublicHostApplicationRouteChildren =
  {
    ApiPublicHostApplicationResendRoute: ApiPublicHostApplicationResendRoute,
  }

const ApiPublicHostApplicationRouteWithChildren =
  ApiPublicHostApplicationRoute._addFileChildren(
    ApiPublicHostApplicationRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRouteWithChildren,
  CommunityRoute: CommunityRoute,
  DiscoverRoute: DiscoverRoute,
  FoundingSalonRoute: FoundingSalonRoute,
  HostRoute: HostRoute,
  HostsRoute: HostsRoute,
  HowItWorksRoute: HowItWorksRoute,
  IrieSupperClubRoute: IrieSupperClubRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MealPrepRoute: MealPrepRoute,
  MolinoRoute: MolinoRoute,
  MolinoJune6Route: MolinoJune6Route,
  MolinoPizzaPopUpRoute: MolinoPizzaPopUpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RichieRoute: RichieRoute,
  SafetyReportRoute: SafetyReportRoute,
  SharePreviewRoute: SharePreviewRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Vintage1986Route: Vintage1986Route,
  AdminChefServiceInfoRoute: AdminChefServiceInfoRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminMolinoRoute: AdminMolinoRoute,
  AdminPaymentsGoLiveRoute: AdminPaymentsGoLiveRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminTastemakersRoute: AdminTastemakersRoute,
  ApiChatRoute: ApiChatRoute,
  ChefHandleRoute: ChefHandleRoute,
  ChefsChefIdRoute: ChefsChefIdRoute,
  ChefsMosheFhimaRoute: ChefsMosheFhimaRoute,
  ChefsRichieMillionJrRoute: ChefsRichieMillionJrRoute,
  ESlugRoute: ESlugRoute,
  E2eShareCardPriceRoute: E2eShareCardPriceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ListingsSlugRoute: ListingsSlugRoute,
  TablesTableIdRoute: TablesTableIdRoute,
  TastemakersTastemakerIdRoute: TastemakersTastemakerIdRoute,
  TastemakersApplyRoute: TastemakersApplyRoute,
  TastemakersIndexRoute: TastemakersIndexRoute,
  AdminPreviewAddressUpdateRoute: AdminPreviewAddressUpdateRoute,
  ApiPublicHostApplicationRoute: ApiPublicHostApplicationRouteWithChildren,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksPaymentsGoLiveReminderRoute:
    ApiPublicHooksPaymentsGoLiveReminderRoute,
  ApiPublicHooksProcessOrderRemindersRoute:
    ApiPublicHooksProcessOrderRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
